# Generated by Django 3.2.4 on 2021-06-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
